#![deny(warnings)]

use crate::cask;
use crate::extractor;
use crate::formula;
use crate::git;
use crate::util;
use crate::util::iso8601;

use std::env;
use std::fs;
use std::fs::File;
use std::io::BufReader;
use std::io::Read;
use std::io::Write;
use std::time::{SystemTime, UNIX_EPOCH};

use eyre::Report;
use serde::Serialize;
use tinytemplate::TinyTemplate;

#[derive(Serialize)]
struct URLTemplateContext {
    name: String,
    bin: String,
    version: String,
}

pub async fn install(
    cask: cask::Cask,
    package_name: &str,
    version: Option<&str>,
) -> Result<(), Report> {
    let cask_git_url = format!("https://{}-cask.git", package_name);

    let unix_time = {
        let start = SystemTime::now();

        let t = start.duration_since(UNIX_EPOCH)?;

        t.as_secs()
    };

    let formula_cloned_dir = env::temp_dir().join(format!("cask_{}", unix_time));
    let cask_file_path = formula_cloned_dir.join("Cask.toml");

    let package_formula = match git::clone(&cask_git_url, &formula_cloned_dir, vec!["--depth", "1"])
    {
        Ok(()) => {
            if !cask_file_path.exists() {
                // remove cloned repo
                fs::remove_dir_all(formula_cloned_dir)?;
                return Err(eyre::format_err!(
                    "{} is not a valid formula!",
                    package_name
                ));
            }

            let f = formula::new(&cask_file_path)?;

            Ok(f)
        }
        Err(e) => Err(e),
    }?;

    let option_target = if cfg!(target_os = "macos") {
        package_formula.darwin.as_ref()
    } else if cfg!(target_os = "windows") {
        package_formula.windows.as_ref()
    } else if cfg!(target_os = "linux") {
        package_formula.linux.as_ref()
    } else {
        fs::remove_dir_all(formula_cloned_dir)?;
        return Err(eyre::format_err!(
            "{} not support your system",
            package_name
        ));
    };

    let target = match option_target {
        Some(p) => Ok(p),
        None => Err(eyre::format_err!(
            "{} not support your system",
            package_name
        )),
    }?;

    let download_version = {
        if let Some(v) = version {
            if !package_formula.package.versions.contains(&v.to_string()) {
                Err(eyre::format_err!(
                    "can not found version '{}' of formula",
                    v
                ))
            } else {
                Ok(v.to_owned())
            }
        } else if let Some(v) = &package_formula.package.version {
            if !package_formula.package.versions.contains(v) {
                Err(eyre::format_err!(
                    "can not found version '{}' of formula",
                    v
                ))
            } else {
                Ok(v.clone())
            }
        } else if package_formula.package.versions.is_empty() {
            Err(eyre::format_err!("can not found any version of formula"))
        } else {
            Ok(package_formula.package.versions[0].clone())
        }
    }?;

    // init formula folder
    cask.init_package(package_name)?;

    let package_dir = cask.package_dir(package_name);
    {
        let cask_file_content = {
            let cask_file = File::open(&cask_file_path)?;
            let mut buf_reader = BufReader::new(&cask_file);
            let mut file_content = String::new();
            buf_reader.read_to_string(&mut file_content)?;

            file_content
        };

        let file_path = &package_dir.join("Cask.toml");

        let mut formula_file = File::create(&file_path)?;

        formula_file.write_all(
            format!(
                r#"# The file is generated by Cask. DO NOT MODIFY IT.
[cask]
package_name = "{}"
created_at = "{}"
version = "{}"

"#,
                package_name,
                iso8601(&SystemTime::now()),
                download_version
            )
            .as_str()
            .as_bytes(),
        )?;
        formula_file.write_all(cask_file_content.as_bytes())?;
    }

    // remove cloned repo
    fs::remove_dir_all(formula_cloned_dir)?;

    let option_arch = if cfg!(target_arch = "x86") {
        target.x86.as_ref()
    } else if cfg!(target_arch = "x86_64") {
        target.x86_64.as_ref()
    } else if cfg!(target_arch = "arm") {
        target.arm.as_ref()
    } else if cfg!(target_arch = "aarch64") {
        target.aarch64.as_ref()
    } else if cfg!(target_arch = "mips") {
        target.mips.as_ref()
    } else if cfg!(target_arch = "mips64") {
        target.mips64.as_ref()
    } else if cfg!(target_arch = "mips64el") {
        target.mips64el.as_ref()
    } else {
        None
    };

    let arch = match option_arch {
        Some(a) => Ok(a),
        None => Err(eyre::format_err!("{} not support your arch", package_name)),
    }?;

    let tar_file_path = &package_dir
        .join("version")
        .join(format!("{}.tar.gz", &download_version));

    // renderer url
    let rendered_url = {
        let render_context = URLTemplateContext {
            name: package_formula.package.name.clone(),
            bin: package_formula.package.bin.clone(),
            version: download_version.clone(),
        };
        let mut tt = TinyTemplate::new();
        tt.add_template("url_template", &arch.url)?;

        tt.render("url_template", &render_context)?
    };

    util::download(&rendered_url, tar_file_path).await?;

    let bin_name = if cfg!(target_os = "windows") {
        format!("{}.exe", &package_formula.package.bin)
    } else {
        package_formula.package.bin.clone()
    };

    let output_file_path = extractor::extract(tar_file_path, &bin_name, &package_dir.join("bin"))?;

    let symlink_file = cask.package_bin_dir(package_name).join(bin_name);
    if symlink_file.exists() {
        fs::remove_file(&symlink_file)?;
    }
    // create soft link in bin folder
    #[cfg(target_family = "unix")]
    std::os::unix::fs::symlink(output_file_path, &symlink_file)?;
    #[cfg(target_family = "windows")]
    std::os::windows::fs::symlink_file(output_file_path, &symlink_file)?;

    Ok(())
}
